### PR TITLE
Remove condition to fix undefined reference

### PR DESCRIPTION
**Pull request by donarturo11**

### CODE REVIEW

**Comment by clbr** [comment]
This looks wrong. I've never hit it, for one. Better find out why the defines are not as intended in your build.

**Comment by donarturo11** [comment]
Do you have any contact way, eg. Discord, IRC, LinkedIn or Messenger, for discuss on way to developing? E.g. for avoid compilation error from TRUE and FALSE, I defined from compiler flags.
Sorry that I'm asking on comment, bur I have no way to contact You.

**Comment by donarturo11** [comment]
> This looks wrong. I've never hit it, for one. Better find out why the defines are not as intended in your build.

Thank you for the advice.

**Comment by clbr** [comment]
Sorry, I don't want to give realtime support. Would take way too much time.

**Comment by donarturo11** [comment]
You are right! Set up right definitions compiles without described bug. So this request can be rejected.

**Pull request closed without merging**
