### PR TITLE
Replace deprecated expression and add definition for include header

### PR DESCRIPTION
**Pull request by donarturo11**

### CODE REVIEW

**Comment by clbr** [comment]
This I can't merge without testing, and given how long webkit builds take, it may be a very long time before I get to it.

**Comment by clbr** [comment]
Google says this would break older bison versions, including the one I have, so I can't add this.

**Comment by donarturo11** [comment]
I would to ask if just adding ```%define api.header.include{"CSSGrammar.h"}``` without rewritting ```@pure-parser``` will be good solution?

**Comment by clbr** [comment]
I'm not sure - I'd have to test if it doesn't break my bison. Which may take a long time.

**Comment by donarturo11** [comment]
At what kind of distros and which version do you work and test this project?

**Comment by clbr** [comment]
Sometimes TinyCore, but mainly LFS. So fairly custom setups.

**Pull request closed without merging**
